version: '3.7'

services:
  app:
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PUBLIC_API_BASE=${PUBLIC_API_BASE:-http://localhost:3001}
      - API_PORT=${API_PORT:-3001}
      - APP_SECRET=${API_SECRET}
      - PASSWORD_SALT=${PASSWORD_SALT}
    build:
      context: .
    depends_on:
      - postgres
    container_name: metatoggle.app
    ports:
      - "3001:3001"

  postgres:
    image: postgres:13.0-alpine
    container_name: metatoggle.postgres
    command: -c 'max_connections=512'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=featureflags
    ports:
      - "5432:5432"